gallery/core/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    
    # path for login, logout and register
    path('register/', views.register, name="register"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    
    # path for gallery browse
    path('gallery/museum/', views.museum, name='museum'),
    path('gallery/<str:gallery_name>/', views.gallery_view, name='gallery'),
    path('gallery/styletag/<str:tag_name>/', views.styletag_detail, name='styletag_detail'),
    path('gallery/artwork/<str:artwork_title>/', views.artwork, name='artwork'),
    path('gallery/author/<str:author_name>/', views.author, name='author'),

    # path for admin pages
    path('manage/gallery/<str:gallery_name>/', views.edit_gallery, name='edit_gallery'),
    path('manage/gallery/<str:gallery_name>/artwork/add/', views.add_artwork_view, name='add_artwork'),
    path('manage/gallery/<str:gallery_name>/artwork/<str:artwork_title>/', views.edit_artwork_view, name='edit_artwork'),
    path('manage/author/add/', views.add_author_view, name='add_author'),
    path('manage/styletag/add/', views.add_styletag_view, name='add_styletag'),

    # path for reservation
    path('reservation/createorder/', views.create_reservation, name='create_reservation'),
    path('get_reservations_count/', views.get_reservations_count, name='get_reservations_count'),
    path('reservation/myreservations/', views.view_my_reservation, name='my_reservation'),

    # path for search
    path('search/', views.search, name='search'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/gallery/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('core.urls')),
]

gallery/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.signals import post_save, post_delete, pre_delete
from django.dispatch import receiver
from django.db.models import Subquery, OuterRef, Avg

import uuid


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True, blank=False)
    
    def __str__(self):
        return self.username


class Gallery(models.Model):
    gallery_name = models.CharField(max_length=300, primary_key=True)
    location = models.CharField(max_length=50)
    description = models.TextField(default="gallery description")
    image = models.ImageField(upload_to='img/gallery', default='img/gallery/default.jpg')
    visitor_capacity = models.IntegerField(default=300)
    rating = models.FloatField(default=3.0)

    def __str__(self):
        return self.gallery_name
    
    def artwork_list(self):
        return self.artwork_set.all()
    
    def get_comments(self):
        return Comment.objects.filter(
            content_type=ContentType.objects.get_for_model(self),
            object_id=self.pk
        )


class Author(models.Model):
    name = models.CharField(max_length=50, primary_key=True)
    description  =  models.TextField(default="Author description")
    rating = models.FloatField(default=3.0)
    
    def __str__(self):
        return self.name
    
    def get_comments(self):
        return Comment.objects.filter(
            content_type=ContentType.objects.get_for_model(self),
            object_id=self.pk
        )        


class Artwork(models.Model):
    title = models.CharField(max_length=50, primary_key=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="artwork")
    description = models.TextField(default="artwork description")
    gallery = models.ForeignKey(Gallery,  on_delete=models.CASCADE, related_name="artwork")
    image = models.ImageField(upload_to='img/artwork')
    rating = models.FloatField(default=3.0)
    year = models.PositiveIntegerField(default=2000)

    def __str__(self):
        return self.title
    
    def get_comments(self):
        return Comment.objects.filter(
            content_type=ContentType.objects.get_for_model(self),
            object_id=self.pk
        ) 



class StyleTag(models.Model):
    tag_name = models.CharField(max_length=50, primary_key=True)
    artwork = models.ManyToManyField(Artwork, related_name="styletag")
    description = models.TextField(default="styletag description")

    def __str__(self):
        return self.tag_name


class ReservationOrder(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user_name =  models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="reservation")
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name="reservation")
    created_time = models.TimeField(auto_now_add=True)
    order_date = models.DateField()
    num_people = models.PositiveIntegerField(
        default=1,
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )

    def __str__(self):
        return f"{self.user_name} - {self.gallery} - {self.order_date} - {self.created_time}"
    


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.CharField(max_length=300) 
    content_object = GenericForeignKey('content_type', 'object_id') 

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    text = models.TextField(default="the user hasn't made comment")
    rating = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(5)],
        null=True,
        blank=True
    )
    created_time = models.DateTimeField(auto_now_add=True)
    is_public = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} comment on {self.content_object} at {self.created_time}"
    
    def save(self, *args, **kwargs):
        # if not self.id:
        #     self.id = f"{self.user.username}_{self.object_id}_{self.created_time}"
        super().save(*args, **kwargs)


# update rating
@receiver(post_save, sender=Comment)
@receiver(post_delete, sender=Comment)
def update_object_average_rating(sender, instance, **kwargs):
    latest_comment_ids = Comment.objects.filter(
        content_type=instance.content_type,
        object_id=instance.object_id,
        rating__isnull=False,
        user=OuterRef('user')
    ).order_by('-created_time').values('id')[:1]

    latest_ratings = Comment.objects.filter(
        id__in=Subquery(latest_comment_ids)
    )
    average_rating = latest_ratings.aggregate(Avg('rating'))['rating__avg']

    content_object = instance.content_object
    content_object.rating = average_rating if average_rating is not None else 4.0
    content_object.save()

# update styletag
@receiver(pre_delete, sender=Artwork)
def remove_artwork_from_styletags(sender, instance, **kwargs):
    for tag in instance.styletag.all():
        tag.artwork.remove(instance)

gallery/core/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.urls import reverse
from django.forms import modelformset_factory
from django.db import IntegrityError
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.db import transaction

from .models import Gallery, Artwork, Author, StyleTag, ReservationOrder
from .forms import CustomUserCreationForm, GalleryForm, ArtworkForm, ArtworkFormSet, AuthorForm, StyleTagForm, ReservationOrderForm
from django.http import HttpResponse
from django.template import loader
from django.db.models import Sum
from datetime import date


# Create your views here.

def home(request):
    """
    Renders the homepage template.
    """
    artworks = Artwork.objects.all()
    recommended_artworks = artworks.order_by('?')[:2]
    context = {'artworks': artworks, 'recommended_artworks': recommended_artworks}
    
    return render(request, 'home.html', context)

def logout_view(request):
    logout(request)
    return redirect('home')

def museum(request):
    galleries = Gallery.objects.all()
    return render(request, 'museum.html', {'galleries': galleries} )

def search(request):
    artworks = Artwork.objects.all()
    query = request.GET.get('query')
    results = artworks.filter(title=query) | artworks.filter(author=query)
    no_results_message = None

    if len(results) == 0:
        no_results_message = 'No matching artworks found.'

    print(results) 
    print(no_results_message)
    context = {'results': results, 'no_results_message': no_results_message}
    return render(request, 'search.html', context )


def gallery_view(request, gallery_name):
    '''
    display the info and all exhibited artworks of a gallery.
    '''
    gallery = Gallery.objects.get(gallery_name=gallery_name)
    #gallery_artworks = Artwork.objects.filter(gallery=gallery)
    gallery_artworks = Artwork.objects.filter(gallery=gallery).select_related('gallery')
    context = {
        'gallery': gallery,
        'artworks': gallery_artworks,
    }
    return render(request, 'gallery.html', context)

def register(request):
    """
    new account register
    """
    if request.method == 'POST':
        register_form = CustomUserCreationForm(request.POST)
        if register_form.is_valid():
            user = register_form.save()
            login(request, user)
            messages.success(request, 'Register Suceed!')
            return redirect('home')
    else:
        register_form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': register_form})


# Views for admin 

@login_required
def edit_gallery(request, gallery_name):
    """
    only staff allowed
    edit the info of the gallery. display all artworks exhibited in the gallery.
    """
    
    if not request.user.is_staff:
        messages.error(request, "Access Denied: Administrator privileges required. Please contact root for access.")
        return redirect('home')
    
    gallery = get_object_or_404(Gallery, gallery_name=gallery_name)
    
    if request.method == 'POST':
        form = GalleryForm(request.POST, request.FILES, instance=gallery)
        #formset = ArtworkFormSet(request.POST, request.FILES, instance=gallery)

        if form.is_valid():
            form.save()
            #formset.save()
            return redirect('edit_gallery', gallery_name=gallery.gallery_name)
    else:
        form = GalleryForm(instance=gallery)
        formset = ArtworkFormSet(instance=gallery)

    return render(request, 'edit_gallery.html', {
        'form': form, 
        'gallery': gallery
    })


@login_required
def edit_artwork_view(request, gallery_name, artwork_title):
    """
    only staff allowed
    change the properity value (except rating score) of an existing artwork.
    """

    if not request.user.is_staff:
        messages.error(request, "Access Denied: Administrator privileges required. Please contact root for access.")
        return redirect('home')

    gallery = get_object_or_404(Gallery, gallery_name=gallery_name)
    artwork = get_object_or_404(Artwork, title=artwork_title, gallery=gallery)

    if request.method == 'POST':

        if 'delete_artwork' in request.POST:
            artwork.delete()
            return redirect('edit_gallery', gallery_name=gallery.gallery_name)
        
        artwork_form = ArtworkForm(request.POST, request.FILES, instance=artwork)
        if artwork_form.is_valid():
            artwork_form.save()

            return redirect('edit_gallery', gallery_name=gallery.gallery_name)
    else:
        artwork_form = ArtworkForm(instance=artwork)

    return render(request, 'edit_artwork.html', {
        'artwork_form': artwork_form,
        'gallery': gallery,
        'artwork': artwork
    })


@login_required
def add_artwork_view(request, gallery_name):
    """
    only staff allowed
    add a new artwork
    """

    if not request.user.is_staff:
        messages.error(request, "Access Denied: Administrator privileges required. Please contact root for access.")
        return redirect('home')
    
    gallery = get_object_or_404(Gallery, gallery_name=gallery_name)
    
    if request.method == 'POST':
        form = ArtworkForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                new_artwork = form.save(commit=False)
                new_artwork.gallery = gallery  
                new_artwork.save()
                form.save_m2m()  
                return redirect('edit_gallery', gallery_name=gallery.gallery_name)
            except IntegrityError:
                form.add_error(None, "There was an error saving the artwork. Please try again.")
    else:
        form = ArtworkForm()
    
    return render(request, 'add_artwork.html', {'form': form, 'gallery': gallery})


@login_required
def add_author_view(request):
    """
    only staff allowed
    add a new author
    """

    if not request.user.is_staff:
        messages.error(request, "Access Denied: Administrator privileges required. Please contact root for access.")
        return redirect('home')

    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            previous_url = request.META.get('HTTP_REFERER')
            return redirect(previous_url) if previous_url else redirect('edit_gallery', gallery_name=request.GET.get('gallery_name'))
    else:
        form = AuthorForm()

    return render(request, 'add_author.html', {'form': form})


@login_required
def add_styletag_view(request):
    """
    only staff allowed
    add a new styletag
    """
    if not request.user.is_staff:
        messages.error(request, "Access Denied: Administrator privileges required. Please contact root for access.")
        return redirect('home')
    
    if request.method == 'POST':
        form = StyleTagForm(request.POST)
        if form.is_valid():
            form.save()
            previous_url = request.META.get('HTTP_REFERER')
            return redirect(previous_url) if previous_url else redirect('edit_gallery', gallery_name=request.GET.get('gallery_name'))
    else:
        form = StyleTagForm()

    return render(request, 'add_styletag.html', {'form': form})


def artwork(request, artwork_title):
    artwork = get_object_or_404(Artwork, title=artwork_title)
    context = {
        'artwork': artwork,
    }
    return render(request, 'artwork.html', context)

def styletag_detail(request, tag_name):
    '''
    display the artworks of a specific style
    '''
    style_tag = get_object_or_404(StyleTag, tag_name=tag_name)
    
    artworks = style_tag.artwork.all()

    return render(request, 'styletag_detail.html', {
        'style_tag': style_tag,
        'artworks': artworks,
    })

    
def author(request, author_name):
    '''
    author introduction page. display all artworks of the same author.
    '''
    try:
        author_found = Author.objects.get(name=author_name)
    except Author.DoesNotExist:
        return HttpResponse("Author not found", status=404)

    artworks = Artwork.objects.filter(author=author_found).select_related('author')
    context = {
        'author': author_found,
        'artworks': artworks,
    }
    return render(request, 'author.html', context)


@login_required
def create_reservation(request):
    '''
    for users to create new reservation
    '''
    current_reservations = None
    capacity = None

    if request.method == 'POST':
        form = ReservationOrderForm(request.POST)
        if form.is_valid():
            gallery = form.cleaned_data['gallery']
            order_date = form.cleaned_data['order_date']
            num_people = form.cleaned_data['num_people']

            with transaction.atomic():
                gallery = Gallery.objects.select_for_update().get(gallery_name=gallery.gallery_name)

                existing_reservation = ReservationOrder.objects.filter(
                    user_name=request.user,
                    order_date=order_date
                ).exists()

                if existing_reservation:
                    form.add_error('order_date', 'You already have a reservation on this date.')
                else:
                    current_reservations = ReservationOrder.objects.filter(
                        gallery=gallery,
                        order_date=order_date
                    ).aggregate(total=Sum('num_people'))['total'] or 0
                    capacity = gallery.visitor_capacity

                    if current_reservations + num_people > capacity:
                        form.add_error(None, "Reservation Fail")
                    else:
                        reservation = form.save(commit=False)
                        reservation.user_name = request.user

gallery/core/templates/add_author.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Add New Author{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow-sm">
                <div class="card-header bg-secondary">
                    <h2 class="text-white h4 mb-0">Add New Author</h2>
                </div>
                
                <div class="card-body p-4">
                    <form action="{% url 'add_author' %}" method="POST">
                        {% csrf_token %}
                        
                        {% for field in form %}
                            <div class="mb-4">
                                <label for="{{ field.id_for_label }}" class="form-label fw-bold">
                                    {{ field.label }}
                                </label>
                                
                                {% if field.name == 'description' %}
                                    {% render_field field class="form-control" rows="4" %}
                                {% else %}
                                    {% render_field field class="form-control" %}
                                {% endif %}
                                
                                {% if field.help_text %}
                                    <div class="form-text text-muted small">
                                        {{ field.help_text }}
                                    </div>
                                {% endif %}
                                
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <div class="invalid-feedback d-block">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        {% endfor %}

                        <div class="mt-4 d-flex justify-content-between align-items-center">
                            <a href="javascript:history.back()" class="btn btn-outline-secondary btn-lg same-size-btn">
                                <i class="bi bi-arrow-left"></i> Back
                            </a>
                            <button type="submit" class="btn btn-outline-success btn-lg same-size-btn">
                                <i class="bi bi-person-plus"></i> Add Author
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>

.card {
    border: none;
    box-shadow: 0 2px 15px rgba(0, 0, 0, 0.08);
    border-radius: 8px;
}

.card-header {
    border-radius: 8px 8px 0 0 !important;
}

.form-label {
    color: #495057;
    font-size: 0.95rem;
}

.form-control {
    padding: 0.75rem;
    border-radius: 6px;
}

.form-control:focus {
    border-color: #4c1370;
    box-shadow: 0 0 0 0.25rem rgba(76, 19, 112, 0.25);
}


.btn-outline-secondary {
    padding: 10px 20px;
}

.btn-outline-secondary:hover {
    background-color: #6c757d;
    color: white;
}

.invalid-feedback {
    color: #dc3545;
    margin-top: 0.25rem;
}

.text-muted {
    font-size: 0.875rem;
}

.same-size-btn {
    padding: 0.8rem 2rem;
    font-size: 1.1rem;
    min-width: 160px;  
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;  
}


@media (max-width: 576px) {
    .same-size-btn {
        min-width: 140px;
        padding: 0.7rem 1.5rem;
    }
}
</style>
{% endblock %}

gallery/core/templates/add_styletag.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Add New Style Tag{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="card shadow-sm">
                <div class="card-header bg-secondary">
                    <h2 class="text-white h4 mb-0">Add New Style Tag</h2>
                </div>
                
                <div class="card-body p-4">
                    <form action="{% url 'add_styletag' %}" method="POST">
                        {% csrf_token %}
                        
                        {% for field in form %}
                            <div class="mb-4">
                                <label for="{{ field.id_for_label }}" class="form-label fw-bold">
                                    {{ field.label }}
                                </label>
                                
                                {% if field.name == 'description' %}
                                    {% render_field field class="form-control" rows="4" %}
                                {% else %}
                                    {% render_field field class="form-control" %}
                                {% endif %}
                                
                                {% if field.help_text %}
                                    <div class="form-text text-muted small">
                                        {{ field.help_text }}
                                    </div>
                                {% endif %}
                                
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <div class="invalid-feedback d-block">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        {% endfor %}

                        <div class="mt-4 d-flex justify-content-between align-items-center">
                            <a href="javascript:history.back()" class="btn btn-outline-secondary same-size-btn">
                                <i class="bi bi-arrow-left"></i> Back
                            </a>
                            <button type="submit" class="btn btn-outline-success btn-lg same-size-btn">
                                <i class="bi bi-tag"></i> Add Style Tag
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.card {
    border: none;
    box-shadow: 0 2px 15px rgba(0, 0, 0, 0.08);
    border-radius: 8px;
}

.card-header {
    border-radius: 8px 8px 0 0 !important;
}

.form-label {
    color: #495057;
    font-size: 0.95rem;
}

.form-control {
    padding: 0.75rem;
    border-radius: 6px;
}

.form-control:focus {
    border-color: #4c1370;
    box-shadow: 0 0 0 0.25rem rgba(76, 19, 112, 0.25);
}

.invalid-feedback {
    color: #dc3545;
    margin-top: 0.25rem;
}

.text-muted {
    font-size: 0.875rem;
}

.same-size-btn {
    padding: 0.8rem 2rem;
    font-size: 1.1rem;
    min-width: 160px;  
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;  
}


@media (max-width: 576px) {
    .same-size-btn {
        min-width: 140px;
        padding: 0.7rem 1.5rem;
    }
}
</style>
{% endblock %}

gallery/core/templates/create_reservation.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Create Reservation Order{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Create Reservation Order</h2>
    <form id="reservationForm" method="post" class="reservation-form">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_gallery">Gallery:</label>
            {{ form.gallery|add_class:"form-control"|attr:"placeholder:Select a gallery" }}
        </div>

        <div class="form-group">
            <label for="id_order_date">Order Date:</label>
            {{ form.order_date|add_class:"form-control"|attr:"placeholder:YYYY-MM-DD" }}
        </div>

        <div class="form-group">
            <label for="id_num_people">Number of People:</label>
            {{ form.num_people|add_class:"form-control"|attr:"placeholder:Enter a number (1-5)" }}
            <small id="numPeopleHint" class="hint">Note: Maximum number of people is 5</small>
        </div>

        <p id="reservationInfo" class="info"></p>

        <div class="d-flex justify-content-center align-items-center">
        <button type="submit" class="submit-btn ">Submit</button>
        </div>
    </form>
</div>

{% if form.errors %}
    <script id="form-errors" type="application/json">
        {
            {% for field, error_list in form.errors.items %}
            "{{ field|escapejs }}": [
                {% for error in error_list %}
                "{{ error|escapejs }}"{% if not forloop.last %},{% endif %}
                {% endfor %}
            ]{% if not forloop.last %},{% endif %}
            {% endfor %}
        }
    </script>
    <script>
        const errorData = JSON.parse(document.getElementById('form-errors').textContent);
        const errors = [];
        for (const [field, fieldErrors] of Object.entries(errorData)) {
            fieldErrors.forEach(error => errors.push(error));
        }
        alert(errors.join("\n"));
    </script>
{% endif %}

<script>
document.addEventListener('DOMContentLoaded', function () {
    const numPeopleInput = document.getElementById('id_num_people');

    numPeopleInput.addEventListener('input', function () {
        if (!Number.isInteger(Number(numPeopleInput.value)) || numPeopleInput.value > 5) {
            alert('Please enter a whole number between 1 and 5.');
            numPeopleInput.value = numPeopleInput.value > 5 ? 5 : Math.floor(numPeopleInput.value);
        }
    });
});

document.addEventListener('DOMContentLoaded', function () {
    const galleryField = document.getElementById('id_gallery');
    const orderDateField = document.getElementById('id_order_date');
    const reservationInfo = document.getElementById('reservationInfo');

    function updateReservationInfo() {
        const galleryName = galleryField.options[galleryField.selectedIndex].text; 
        const orderDate = orderDateField.value;

        if (galleryName && orderDate) {
            fetch(`/get_reservations_count/?gallery_name=${encodeURIComponent(galleryName)}&order_date=${orderDate}`)
                .then(response => response.json())
                .then(data => {
                    if (data.error) {
                        reservationInfo.textContent = 'Error loading reservation data.';
                    } else {
                        reservationInfo.textContent = `Number of reservations for the selected date: ${data.current_reservations} / ${data.capacity}`;
                    }
                });
        }
    }

    galleryField.addEventListener('change', updateReservationInfo);
    orderDateField.addEventListener('change', updateReservationInfo);
});
</script>
{% endblock %}

gallery/core/templates/register.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Register</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>

        .form-signin {
            max-width: 600px;
            width: 100%;
            margin: auto;
        }

        .center-screen {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .btn-purple {
            background-color: #6f42c1;
            color: white;
            border-color: #6f42c1;
        }

        .btn-purple:hover {
            background-color: #5a3799; 
            border-color: #5a3799;
        }


        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style>

    <link href="{% static 'css/header.css' %}" rel="stylesheet">
</head>
<body class="text-center">
    <div class="center-screen">
    <main class="form-signin">
        <form method="post" class="w-50 mx-auto">
            {% csrf_token %}
            <img class="mb-4" src="{% static 'svg/logo.svg' %}" alt="Logo" width="72" height="57">
            <h1 class="h3 mb-3 fw-normal">Register</h1>

            <div class="form-floating mb-3">
                {{ form.username|add_class:"form-control" }}
                <label for="id_username">Username</label>
            </div>

            <div class="form-floating mb-3">
                {{ form.email|add_class:"form-control" }}
                <label for="id_email">Email</label>
            </div>

            <div class="form-floating mb-3">
                {{ form.password1|add_class:"form-control" }}
                <label for="id_password1">Password</label>
            </div>

            <div class="form-floating mb-3">
                {{ form.password2|add_class:"form-control" }}
                <label for="id_password2">Confirm Password</label>
            </div>


            <button class="w-100 btn btn-lg btn-purple" type="submit">Sign Up</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2024–2025</p>
        </form>
    </main>
    </div>
</body>
</html>